language: python
dist: bionic
os: linux
python:
  - "3.11"
install:
  - pip install -r requirements.txt

script:
  - black ./mysite ./polls
  - black --check ./mysite ./polls
  - flake8 ./mysite ./polls
  - coverage run --source='polls,mysite' manage.py test